11.RailsCrud/Rolodex/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :contacts

end

11.RailsCrud/Rolodex/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.find params[:id]
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create que_params
    redirect_to root_path
  end

  def edit
    @contact = Contact.find params[:id]
  end

  def update
    @contact = Contact.find params[:id]
    @contact.update_attributes que_params
    redirect_to root_path
  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.delete
    redirect_to root_path
  end

private
  def que_params
    params.require(:contact).permit(:name)
  end

end

11.RailsCrud/Rolodex/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contacts = Contact.all
  end
end

11.RailsCrud/Rolodex/app/views/contacts/_form.html.erb
<% form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

11.RailsCrud/Rolodex/app/views/contacts/edit.html.erb
<h2>Edit Contact</h2>

<%=  form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

11.RailsCrud/Rolodex/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

11.RailsCrud/Rolodex/app/views/contacts/show.html.erb
<h2>Show Data</h2>

<%= @contact.name %>
<%= link_to "Home", root_path %>

11.RailsCrud/Rolodex/app/views/home/index.html.erb
<h2>Yes!</h2>

<%= link_to "New Contact", new_contact_path %>
<br>
<% @contacts.each do |contact| %>
  <%= link_to contact.name, contact_path(contact) %>
  <%= link_to "Edit", edit_contact_path(contact) %>
  <%= link_to "Delete", contact_path(contact), method: :delete %>
  <br>
<% end %>