00.Practice/RailsApp/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :patients

end

00.Practice/RailsApp/app/models/patient.rb
class Patient < ActiveRecord::Base
end

00.Practice/RailsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

00.Practice/RailsApp/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @patients = Patient.all
  end

end

00.Practice/RailsApp/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create accepted_params
    redirect_to(root_path)
  end

  private
    def accepted_params
      params.require(:patient).permit(
              :first_name, 
              :last_name
      )
    end

end

00.Practice/RailsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

00.Practice/RailsApp/app/helpers/home_helper.rb
module HomeHelper
end

00.Practice/RailsApp/app/helpers/patients_helper.rb
module PatientsHelper
end

00.Practice/RailsApp/app/views/home/index.html.erb
<h3>Home</h3>
<%= link_to "Create Patient", new_patient_path %>
<br>

<% @patients.each do |patient| %>
  <%= patient.first_name %>
  <%= patient.last_name %>
  <br>
<% end %>  

00.Practice/RailsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

00.Practice/RailsApp/app/views/patients/new.html.erb
<h3>New Patient Form</h3>
<%= form_for @patient do |f| -%>
  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name %>
  <%= f.submit "Create" %>
<% end -%>